apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certmanager-applicationset
spec:
  generators:
  - list:
      elements:
#      - cluster: core
#        url: https://kubernetes.default.svc
      - cluster: carslen-hotel-budapest
        url: https://carslendemobudapest-dns-9bd4168d.hcp.germanywestcentral.azmk8s.io

  template:
    metadata:
      name: '{{ cluster }}-certmanager'
      labels:
        app: cert-manager-label
    spec:
      project: default
      source:
        chart: cert-manager
        helm:
          valueFiles:
            - https://raw.githubusercontent.com/catenax-ng/k8s-cluster-stack/feature/A10DT-419-setup-default-apps/apps/certmanager/values.certmanager.yaml
        repoURL: https://charts.jetstack.io
        targetRevision: v1.7.2
        #repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        #targetRevision: feature/A10DT-419-setup-default-apps
        #path: apps/certmanager
      # TODO 24.03.2022 CARSLEN: Might it be usefull to install to an own namespace, i.e. cert-manager, as docu suggests?
      ignoreDifferences: # https://github.com/argoproj/argo-cd/issues/4276#issuecomment-908455476
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: '{{ cluster }}-certmanager-cert-manager-webhook'
          jsonPointers:
            - /webhooks/0/namespaceSelector/matchExpressions/2
      destination:
        server: '{{ url }}'
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
